targets:
  $default:
    sources:
      - lib/**
      - swaggers/**
      - swaggers2/**
      - swagger_examples/**
      - $package$
    builders:
      chopper_generator:
        options:
          header: "// Generated code"
      swagger_dart_code_generator:
        options:
          include_if_null:
            enabled: true
            value: true
          with_converter: true
          input_folder: "lib/src/rest/"
          output_folder: "lib/src/rest/"
          enums_case_sensitive: true